In [67]:
import numpy as np
import itertools

Some Matrix functions:

In [68]:
def dag(M):
    return np.conjugate(M.T)
def matInv(M):
    return np.linalg.inv(M)
def is_eq(A,B):
    return np.array_equal(A,B)

In [69]:
A = np.array([[0, 1.j],[-1.j, 0]])
print(A)
print(is_eq(dag(A), matInv(A)))

[[ 0.+0.j  0.+1.j]
 [-0.-1.j  0.+0.j]]
True


## Fusion Rules Calculations for $D_4$

Using the Verlinde formula to get S-matrix and then using that to extract the fusion rules $N_{\mathcal{A}\mathcal{B}}^{\mathcal{C}}$:

$\mathcal{S}_{\mathcal{A}\mathcal{B}} = \frac{1}{|G|}\sum_{h_i^A \in C_A, h_j^B \in C_B, h^A_i h^B_j = h^B_j h^A_i} \chi^A((x_i^A)^{-1}h_j^B x_i^A)\chi^B((x_j^B)^{-1}h_i^A x_j^B)$,

where $h_i^A = x_i^A h_1^A(x_i^A)^{-1} = h_1^A$ which is a $C_A$ representative.

$N_{\mathcal{A}\mathcal{B}}^{\mathcal{C}} = \sum_\mathcal{L} \frac{\mathcal{S}_{\mathcal{A}\mathcal{L}}\mathcal{S}_{\mathcal{B}\mathcal{L}}\mathcal{S}_{\mathcal{C}\mathcal{L}}^*}{\mathcal{S}_{\mathcal{0}\mathcal{L}}}$.

In [70]:
R = np.array([[0, -1],[1, 0]])
M = np.array([[1, 0],[0, -1]])
G = np.zeros([2,2,8])
G[:,:,0] = np.eye(2) # The D_4 group
G[:,:,1] = R
G[:,:,2] = R@R
G[:,:,3] = R@R@R
G[:,:,4] = M
G[:,:,5] = M@R
G[:,:,6] = M@R@R
G[:,:,7] = M@R@R@R

C_e = np.array([0])  # Conj Classes
C_r = np.array([1,3])
C_rr = np.array([2])
C_m = np.array([4,6])
C_mr = np.array([5,7])

X_e = np.array([0]) # Coset Representatives
X_r = np.array([0,4])
X_rr = np.array([0])
X_m = np.array([0,3])
X_mr = np.array([0,3])

def triv(x):
    return 1
def a_r(x):
    if (x in C_mr) or (x in C_m):
        return -1
    else:
        return 1
def a_mr(x):
    if (x in C_r) or (x in C_m):
        return -1
    else:
        return 1
def a_m(x):
    if (x in C_mr) or (x in C_r):
        return -1
    else:
        return 1
def e(x):
    if (x in C_e):
        return 2
    elif (x in C_rr):
        return -2
    else:
        return 0
def E(x):
    return G[:,:,x] # Faithful 2d Rep
def b_i(x):
    if (x in [4,5,6,7]):
        return -1
    elif (x in [0,2]):
        return 1
    else:
        return 0
def b_j(x):
    if (x in [2,6,7]):
        return -1
    elif (x in [0,4,5]):
        return 1
    else:
        return 0
def b_k(x):
    if (x in [2,4,5]):
        return -1
    elif (x in [0,6,7]):
        return 1
    else:
        return 0
def om_1(x):
    if (x in [0,1,2,3]):
        return (1.j**x)
    else:
        return 0
def om_2(x):
    if (x in [0,1,2,3]):
        return (1.j**(2*x))
    else:
        return 0
def om_3(x):
    if (x in [0,1,2,3]):
        return (1.j**(3*x))
    else:
        return 0

def index(h, G):
    for i in range(8): # to be generalised
        if np.array_equal(h, G[:,:,i]):
            return i

def matInv(M):
    return np.linalg.inv(M)

def inv(x, G):
    for i in range(8): # to be generalised
        if np.array_equal(matInv(G[:,:,x]), G[:,:,i]):
            return i

Particles = [(0, C_e, X_e, triv),(1, C_rr, X_rr, triv),(2, C_e, X_e, a_r),(3, C_e, X_e, a_mr),(4, C_e, X_e, a_m),(5, C_rr, X_rr, a_r),(6, C_rr, X_rr, a_mr),(7, C_rr, X_rr, a_m),(8, C_e, X_e, e),(9, C_rr, X_rr, e),\
    (10, C_r, X_r, triv), (11, C_r, X_r, om_1), (12, C_r, X_r, om_2), (13, C_r, X_r, om_3),\
        (14, C_m, X_m, triv), (15, C_m, X_m, b_i), (16, C_m, X_m, b_j), (17, C_m, X_m, b_k),\
            (18, C_mr, X_mr, triv), (19, C_mr, X_mr, b_i), (20, C_mr, X_mr, b_j), (21, C_mr, X_mr, b_k)]

Particles_lab_D = [('0', 'C_e', 'X_e', 'triv'),('1', 'C_rr', 'X_rr', 'triv'),('2', 'C_e', 'X_e', 'a_r'),('3', 'C_e', 'X_e', 'a_mr'),('4', 'C_e', 'X_e', 'a_m'),('5', 'C_rr', 'X_rr', 'a_r'),('6', 'C_rr', 'X_rr', 'a_mr'),('7', 'C_rr', 'X_rr', 'a_m'),('8', 'C_e', 'X_e', 'e'),('9', 'C_rr', 'X_rr', 'e'),\
    ('10', 'C_r', 'X_r', 'triv'), ('11', 'C_r', 'X_r', 'om_1'), ('12', 'C_r', 'X_r', 'om_2'), ('13', 'C_r', 'X_r', 'om_3'),\
        ('14', 'C_m', 'X_m', 'triv'), ('15', 'C_m', 'X_m', 'b_i'), ('16', 'C_m', 'X_m', 'b_j'), ('17', 'C_m', 'X_m', 'b_k'),\
            ('18', 'C_mr', 'X_mr', 'triv'), ('19', 'C_mr', 'X_mr', 'b_i'), ('20', 'C_mr', 'X_mr', 'b_j'), ('21', 'C_mr', 'X_mr', 'b_k')]

S = np.zeros([22,22], complex)
for i, C_i, X_i, char_i in Particles:
    for j, C_j, X_j, char_j in Particles:
        sum = 0 
        for i_class, elem_i_class in enumerate(C_i):
            for j_class, elem_j_class in enumerate(C_j):
                if np.array_equal(G[:,:,elem_i_class]@G[:,:,elem_j_class], G[:,:,elem_j_class]@G[:,:,elem_i_class]):
                    sum+=char_i(index(matInv(G[:,:,X_i[i_class]])@G[:,:,elem_j_class]@G[:,:,X_i[i_class]], G))*char_j(index(matInv(G[:,:,X_j[j_class]])@G[:,:,elem_i_class]@G[:,:,X_j[j_class]], G))
        S[i,j] = sum

S_D = S/8
# print('\n'.join([''.join(['{:4}'.format(item) for item in row]) 
#      for row in S]))
N_D = np.zeros([22,22,22])
for I in range(22):
    for J in range(22):
        for K in range(22):
            for L in range(22):
                N_D[I,J,K] += np.real(S_D[I,L]*S_D[J,L]*np.conj(S_D[K,L])/S_D[0,L])

In [71]:
an_1 = 5
an_2 = 10
print('S_{aa}='+str(S_D[an_1, an_1]))
print('S_{bb}='+str(S_D[an_2, an_2]))
print('S_{ab}='+str(S_D[an_1, an_2]))
print('S_{ba}='+str(S_D[an_2, an_1]))
print('S_{0a}='+str(S_D[0, an_2]))
print('S_{a0}='+str(S_D[an_2, 0]))
print('S_{0a}='+str(S_D[0, an_1]))
print('S_{a0}='+str(S_D[an_1, 0]))

S_{aa}=(0.125+0j)
S_{bb}=(0.5+0j)
S_{ab}=(0.25+0j)
S_{ba}=(0.25+0j)
S_{0a}=(0.25+0j)
S_{a0}=(0.25+0j)
S_{0a}=(0.125+0j)
S_{a0}=(0.125+0j)


In [72]:
i_1 = 10 # Prints fusion rules
i_2 = 10
print(Particles_lab_D[i_1],'x', Particles_lab_D[i_2], '=')
for i, indicator in enumerate(N_D[i_1,i_2,:]):
    if indicator != 0:
        print(int(indicator),'x', Particles_lab_D[i])
S_r = 8*np.real(S)

('10', 'C_r', 'X_r', 'triv') x ('10', 'C_r', 'X_r', 'triv') =
1 x ('0', 'C_e', 'X_e', 'triv')
1 x ('1', 'C_rr', 'X_rr', 'triv')
1 x ('2', 'C_e', 'X_e', 'a_r')
1 x ('5', 'C_rr', 'X_rr', 'a_r')


## Fusion Rule Calculations for $Q_8$

In [95]:
I = np.array([[1.j, 0],[0, -1.j]])
J = np.array([[0, -1],[1, 0]])
K = np.array([[0, -1.j],[-1.j, 0]])
G = np.zeros([2,2,8], complex)
G[:,:,0] = np.eye(2) # The Q_8 group
G[:,:,1] = -np.eye(2)
G[:,:,2] = I
G[:,:,3] = -I
G[:,:,4] = J
G[:,:,5] = -J
G[:,:,6] = K
G[:,:,7] = -K

C_e = np.array([0])  # Conj Classes
C_m = np.array([1])
C_1 = np.array([2,3])
C_2 = np.array([4,5])
C_3 = np.array([6,7])
# i - 1 ; j - 2 ; k - 3 !!!

Z_e = np.array([0, 1, 2, 3, 4, 5, 6, 7])  # Centers Classes
Z_m = np.array([0, 1, 2, 3, 4, 5, 6, 7])
Z_1 = np.array([0, 2, 1, 3])
Z_2 = np.array([0, 4, 1, 5])
Z_3 = np.array([0, 6, 1, 7])

X_e = np.array([0]) # Coset Representatives q_c
X_m = np.array([0])
X_1 = np.array([0,4])
X_2 = np.array([0,6])
X_3 = np.array([0,2])

In [74]:

def triv(x):
    return 1
def a_1(x):
    if (x in C_2) or (x in C_3):
        return -1
    else:
        return 1
def a_2(x):
    if (x in C_1) or (x in C_3):
        return -1
    else:
        return 1
def a_3(x):
    if (x in C_1) or (x in C_2):
        return -1
    else:
        return 1
def e(x):
    if (x in C_e):
        return 2
    elif (x in C_m):
        return -2
    else:
        return 0
def E(x):
    return G[:,:,x] # the 2d faithful rep
def om_1(x):
    if x in [0]:
        return 1
    elif x in [1]:
        return -1
    elif x in [2,4,6]:
        return 1.j
    elif x in [3,5,7]:
        return -1.j
def om_2(x):
    if x in [0]:
        return 1
    elif x in [1]:
        return 1
    elif x in [2,4,6]:
        return -1
    elif x in [3,5,7]:
        return -1
def om_3(x):
    if x in [0]:
        return 1
    elif x in [1]:
        return -1
    elif x in [2,4,6]:
        return -1.j
    elif x in [3,5,7]:
        return 1.j


In [103]:

def q(c):
    Q_C = [0, 0, 0, 4, 0, 6, 0, 2] # This for q_c instead
    return Q_C[c]
def grp_i(i):
    return matInv(G[:,:,i])

def index(h):
    for i in range(8): # to be generalised
        if np.array_equal(h, G[:,:,i]):
            return i

def inv(x):
    for i in range(8): # to be generalised
        if np.array_equal(matInv(G[:,:,x]), G[:,:,i]):
            return i

def grp(x):
    return G[:,:, x] # USE G AS A GLOBAL VAR!!! ---- CAREFUL !

Particles = [(0, C_e, X_e, triv),(1, C_m, X_m, triv),(2, C_e, X_e, a_1),(3, C_e, X_e, a_2),(4, C_e, X_e, a_3),(5, C_m, X_m, a_1),(6, C_m, X_m, a_2),(7, C_m, X_m, a_3),(8, C_e, X_e, e),(9, C_m, X_m, e),\
    (10, C_1, X_1, triv), (11, C_1, X_1, om_1), (12, C_1, X_1, om_2), (13, C_1, X_1, om_3),\
        (14, C_2, X_2, triv), (15, C_2, X_2, om_1), (16, C_2, X_2, om_2), (17, C_2, X_2, om_3),\
            (18, C_3, X_3, triv), (19, C_3, X_3, om_1), (20, C_3, X_3, om_2), (21, C_3, X_3, om_3),]
Particles_Q = Particles
Particles_lab_Q = [('0', 'C_e', 'X_e', 'triv'),('1', 'C_m', 'X_m', 'triv'),('2', 'C_e', 'X_e', 'a_1'),('3', 'C_e', 'X_e', 'a_2'),('4', 'C_e', 'X_e', 'a_3'),('5', 'C_m', 'X_m', 'a_1'),('6', 'C_m', 'X_m', 'a_2'),('7', 'C_m', 'X_m', 'a_3'),('8', 'C_e', 'X_e', 'e'),('9', 'C_m', 'X_m', 'e'),\
    ('10', 'C_1', 'X_1', 'triv'), ('11', 'C_1', 'X_1', 'om_1'), ('12', 'C_1', 'X_1', 'om_2'), ('13', 'C_1', 'X_1', 'om_3'),\
        ('14', 'C_2', 'X_2', 'triv'), ('15', 'C_2', 'X_2', 'om_1'), ('16', 'C_2', 'X_2', 'om_2'), ('17', 'C_2', 'X_2', 'om_3'),\
            ('18', 'C_3', 'X_3', 'triv'), ('19', 'C_3', 'X_3', 'om_1'), ('20', 'C_3', 'X_3', 'om_2'), ('21', 'C_3', 'X_3', 'om_3'),]

S = np.zeros([22,22], complex)
for i, C_i, X_i, char_i in Particles:
    for j, C_j, X_j, char_j in Particles:
        sum = 0 
        for i_class, elem_i_class in enumerate(C_i):
            for j_class, elem_j_class in enumerate(C_j):
                if np.array_equal(G[:,:,elem_i_class]@G[:,:,elem_j_class], G[:,:,elem_j_class]@G[:,:,elem_i_class]):
                    sum+=char_i(index(matInv(G[:,:,X_i[i_class]])@G[:,:,elem_j_class]@G[:,:,X_i[i_class]]))*char_j(index(matInv(G[:,:,X_j[j_class]])@G[:,:,elem_i_class]@G[:,:,X_j[j_class]]))
        S[i,j] = sum

S_Q = S/8
# print('\n'.join([''.join(['{:4}'.format(item) for item in row]) 
#      for row in S]))
N_Q = np.zeros([22,22,22])
for I in range(22):
    for J in range(22):
        for K in range(22):
            for L in range(22):
                N_Q[I,J,K] += np.real(S_Q[I,L]*S_Q[J,L]*np.conj(S_Q[K,L])/S_Q[0,L])

In [76]:
an_1 = 5
an_2 = 10
print('S_{aa}='+str(S_Q[an_1, an_1]))
print('S_{bb}='+str(S_Q[an_2, an_2]))
print('S_{ab}='+str(S_Q[an_1, an_2]))
print('S_{ba}='+str(S_Q[an_2, an_1]))
print('S_{0a}='+str(S_Q[0, an_2]))
print('S_{a0}='+str(S_Q[an_2, 0]))
print('S_{0a}='+str(S_Q[0, an_1]))
print('S_{a0}='+str(S_Q[an_1, 0]))

S_{aa}=(0.125+0j)
S_{bb}=(0.5+0j)
S_{ab}=(0.25+0j)
S_{ba}=(0.25+0j)
S_{0a}=(0.25+0j)
S_{a0}=(0.25+0j)
S_{0a}=(0.125+0j)
S_{a0}=(0.125+0j)


In [104]:
i_1 = 14 # Prints fusion rules
i_2 = 14
print(Particles_lab_Q[i_1],'x', Particles_lab_Q[i_2], '=')
for i, indicator in enumerate(N_Q[i_1,i_2,:]):
    if indicator != 0:
        print(int(indicator),'x', Particles_lab_Q[i])
S_r = 8*np.real(S)

('14', 'C_2', 'X_2', 'triv') x ('14', 'C_2', 'X_2', 'triv') =
1 x ('0', 'C_e', 'X_e', 'triv')
1 x ('1', 'C_m', 'X_m', 'triv')
1 x ('3', 'C_e', 'X_e', 'a_2')
1 x ('6', 'C_m', 'X_m', 'a_2')


## R- Symbol Calculation

Imagine we hace a space $\mathcal{H} = \mathcal{H}_b \otimes \mathcal{H}_a$ we can project down to the space of irreducible representations by $\mathcal{P}_{c}^{ba} \propto \sum_{c \in C_c}\sum_{h \in G}\sum_{z \in Z(r)}\chi(z)^* B_h^b A_{q_c z \bar{q}_c}^b \otimes B_{h^{-1}c}^a A_{q_c z \bar{q}_c}^a$.

The braiding action $\mathcal{B}_{ab}: \mathcal{H}_a\otimes\mathcal{H}_b\rightarrow\mathcal{H}_b\otimes\mathcal{H}_a$ is given by: $Flip \circ (\sum_g A_g^a \otimes B_g^b)$.

Combining the two facts we can evaluate the R-symbol as: $\mathcal{R}_c^{ab} \propto \text{Tr} \{\sum_{c \in C_c}\sum_{z \in Z(r_c)}\sum_{h \in G}\sum_{g \in G}\chi(z)^* B_h^b A_{q_c z \bar{q}_c}^b B_g^b \otimes B_{h^{-1}c}^a A_{q_c z \bar{q}_c}^a A_g^a\} $

Finaly: $\mathcal{R}_c^{ab} \propto \text{Tr} \{\sum_{c \in C_c}\sum_{z \in Z(r_c)}\sum_{h \in G}\chi(z)^* A_{q_c z \bar{q}_c}^b B_h^b \otimes A_{q_c z \bar{q}_c h}^a B_{h^{-1}c}^a \} $, with condition $|\mathcal{R}_c^{ab}| = 1$.

### $Q_8$

Defining $D(Q_8)$ representation matrices

$A_g:$
- Flux Free

In [78]:
def A_rep_1(x):
    A_i = np.array([1])
    A_j = np.array([1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_2(x):
    A_i = np.array([1])
    A_j = np.array([1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_3(x):
    A_i = np.array([+1])
    A_j = np.array([-1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_4(x):
    A_i = np.array([-1])
    A_j = np.array([+1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_5(x):
    A_i = np.array([-1])
    A_j = np.array([-1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_6(x):
    A_i = np.array([+1])
    A_j = np.array([-1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_7(x):
    A_i = np.array([-1])
    A_j = np.array([+1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_8(x):
    A_i = np.array([-1])
    A_j = np.array([-1])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_9(x):
    A_i = np.array([[1.j, 0],[0, -1.j]])
    A_j = np.array([[0, -1],[1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_10(x):
    A_i = np.array([[1.j, 0],[0, -1.j]])
    A_j = np.array([[0, -1],[1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i

- {i} Flux

In [79]:
def A_rep_11(x):
    A_i = np.array([[1, 0],[0, 1]])
    A_j = np.array([[0, 1],[1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_12(x):
    A_i = np.array([[1.j, 0],[0, -1.j]])
    A_j = np.array([[0, -1],[1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_13(x):
    A_i = np.array([[-1, 0],[0, -1]])
    A_j = np.array([[0, 1],[1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_14(x):
    A_i = np.array([[-1.j, 0],[0, 1.j]])
    A_j = np.array([[0, -1],[1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i

- {j} Flux

In [80]:
def A_rep_15(x):
    A_i = np.array([[0, 1],[1, 0]])
    A_j = np.array([[1, 0],[0, 1]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_16(x):
    A_i = np.array([[0, -1.j],[-1.j, 0]])
    A_j = np.array([[1.j, 0],[0, -1.j]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_17(x):
    A_i = np.array([[0, -1],[-1, 0]])
    A_j = np.array([[-1, 0],[0, -1]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_18(x):
    A_i = np.array([[0, 1.j],[1.j, 0]])
    A_j = np.array([[-1.j, 0],[0, 1.j]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i

- {k} Flux

In [81]:
def A_rep_19(x):
    A_i = np.array([[0, 1],[1, 0]])
    A_j = np.array([[0, 1],[1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_20(x):
    A_i = np.array([[0, -1],[1, 0]])
    A_j = np.array([[0, -1.j],[-1.j, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_21(x):
    A_i = np.array([[-0, 1],[1, 0]])
    A_j = np.array([[0, -1],[-1, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i
def A_rep_22(x):
    A_i = np.array([[0, -1],[1, 0]])
    A_j = np.array([[0, 1.j],[1.j, 0]])
    if x in [0]:
        return A_i@A_i@A_i@A_i
    elif x in [1]:
        return A_i@A_i
    elif x in [2]:
        return A_i
    elif x in [3]:
        return A_i@A_i@A_i
    elif x in [4]:
        return A_j
    elif x in [5]:
        return A_j@A_j@A_j
    elif x in [6]:
        return A_i@A_j
    else:
        return A_j@A_i

In [82]:
A_mats = [A_rep_1, A_rep_2, A_rep_3, A_rep_4, A_rep_5, A_rep_6, A_rep_7, A_rep_8, A_rep_9, A_rep_10, A_rep_11, A_rep_12, A_rep_13, A_rep_14, A_rep_15, A_rep_16, A_rep_17, A_rep_18, A_rep_19, A_rep_20, A_rep_21, A_rep_22]

$B_h:$
- Flux Free

In [83]:
def B_rep_e(x):
    if x in [0]:
        return np.array([1])
    else:
        return np.array([0])
def B_rep_m(x):
    if x in [1]:
        return np.array([1])
    else:
        return np.array([0])
def B_rep_e_2d(x):
    if x in [0]:
        return np.array([[1, 0],[0, 1]])
    else:
        return np.array([[0, 0],[0, 0]])
def B_rep_m_2d(x):
    if x in [1]:
        return np.array([[1, 0],[0, 1]])
    else:
        return np.array([[0, 0],[0, 0]]) 

- {i} Flux

In [84]:
def B_rep_i(x):
    if x in [2]:
        return np.array([[1, 0],[0, 0]])
    if x in [3]:
        return np.array([[0, 0],[0, 1]])
    else:
        return np.array([[0, 0],[0, 0]])

- {j} Flux

In [85]:
def B_rep_j(x):
    if x in [4]:
        return np.array([[1, 0],[0, 0]])
    if x in [5]:
        return np.array([[0, 0],[0, 1]])
    else:
        return np.array([[0, 0],[0, 0]])

- {k} Flux

In [86]:
def B_rep_k(x):
    if x in [6]:
        return np.array([[1, 0],[0, 0]])
    if x in [7]:
        return np.array([[0, 0],[0, 1]])
    else:
        return np.array([[0, 0],[0, 0]])

In [87]:
B_mats = [B_rep_e, B_rep_m, B_rep_e, B_rep_e, B_rep_e, B_rep_m, B_rep_m, B_rep_m, B_rep_e_2d, B_rep_m_2d, B_rep_i, B_rep_i, B_rep_i, B_rep_i, B_rep_j, B_rep_j, B_rep_j, B_rep_j, B_rep_k, B_rep_k, B_rep_k, B_rep_k]

In [88]:
Z_s = [Z_e, Z_m, Z_e, Z_e, Z_e, Z_m, Z_m, Z_m, Z_e, Z_m, Z_1, Z_1, Z_1, Z_1, Z_2, Z_2, Z_2, Z_2, Z_3, Z_3, Z_3, Z_3]

In [89]:
Dim_s = [1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2]

In [181]:
def r_symbol(an_1, an_2, an_3):
    return np.trace(rep_proj(an_2, an_1, an_3)@braid(rep_proj(an_1, an_2, an_3), an_1, an_2))

def rep_proj(an_1, an_2, an_3):
    d_1 = Dim_s[an_1]
    d_2 = Dim_s[an_2]
    d_3 = Dim_s[an_3]
    Z_1 = Z_s[an_1]
    Z_2 = Z_s[an_2]
    Z_3 = Z_s[an_3]
    A_1 = A_mats[an_1]
    A_2 = A_mats[an_2]
    A_3 = A_mats[an_3]
    B_1 = B_mats[an_1]
    B_2 = B_mats[an_2]
    B_3 = B_mats[an_3]
    (id_1, C_1, X_1, char_1) = Particles_Q[an_1]
    (id_2, C_2, X_2, char_2) = Particles_Q[an_2]
    (id_3, C_3, X_3, char_3) = Particles_Q[an_3]

    Res = np.zeros([d_1*d_2,d_1*d_2])

    for c in C_3:
        for z in Z_3:
            for z_2 in Z_3:
                for h in range(8):
                    Res += np.conjugate(char_3(z))*np.kron( B_1( index( grp_i(h)@grp(c) ) ) @ A_1(index( grp(q(c))@grp(z)@grp_i(q(c)) )),
                    B_2(h) @ A_2(index( grp(q(c))@grp(z)@grp_i(q(c)) )) )
    return d_3/8/d_1/d_2*Res

def flip(B, an_1, an_2): # assume kron(M_a, M_b) has incides (a,b) = a*dim_b +b
    d_1 = Dim_s[an_1]
    d_2 = Dim_s[an_2]
    T = np.zeros([d_1*d_2, d_1*d_2])
    for i in range(d_1):
        for j in range(d_2):
            for m in range(d_2):
                for n in range(d_1):
                    if i == n and j == m:
                        T[m*d_1+n, i*d_2 + j] = 1
    return matInv(T) @ B @ T

def braid(B, an_1, an_2):
    d_1 = Dim_s[an_1]
    d_2 = Dim_s[an_2]
    d_3 = Dim_s[an_3]
    Z_1 = Z_s[an_1]
    Z_2 = Z_s[an_2]
    Z_3 = Z_s[an_3]
    A_1 = A_mats[an_1]
    A_2 = A_mats[an_2]
    A_3 = A_mats[an_3]
    B_1 = B_mats[an_1]
    B_2 = B_mats[an_2]
    B_3 = B_mats[an_3]
    (id_1, C_1, X_1, char_1) = Particles_Q[an_1]
    (id_2, C_2, X_2, char_2) = Particles_Q[an_2]
    (id_3, C_3, X_3, char_3) = Particles_Q[an_3]

    T = np.zeros([d_1*d_2, d_1*d_2])

    for g in range(8):
        T += np.kron(A_1(g), B_2(g))
    print(T)
    print(B)
    return flip(matInv(T)@B@T,an_1, an_2)
      

def fusion_and_braid(an_1, an_2): # Depends on a lot of outside variables!!!
    print(Particles_lab_Q[an_1],'x', Particles_lab_Q[an_2], '=')
    for i, indicator in enumerate(N_Q[an_1,an_2,:]):
        if indicator != 0:
            # Calculate the R-Symbol


            print(int(indicator),'x', Particles_lab_Q[i])
    S_r = 8*np.real(S)

In [186]:
fusion_and_braid(14,14)

('14', 'C_2', 'X_2', 'triv') x ('14', 'C_2', 'X_2', 'triv') =
1 x ('0', 'C_e', 'X_e', 'triv')
1 x ('1', 'C_m', 'X_m', 'triv')
1 x ('3', 'C_e', 'X_e', 'a_2')
1 x ('6', 'C_m', 'X_m', 'a_2')


In [188]:
an_1 = 14
an_2 = 14
an_3 = 6
P = rep_proj(an_1,an_2, an_3)
print(P)
print(P@P)
print(r_symbol(an_1, an_2, an_3))

[[ 1.  0.  0. -1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [-1.  0.  0.  1.]]
[[ 2.  0.  0. -2.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [-2.  0.  0.  2.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.  0.  0. -1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [-1.  0.  0.  1.]]
4.0
